[tools]
go = "1.24"
golangci-lint = "2.2.2"
lefthook = "1.12.2"

[tasks.test]
run = "go test -v ./..."
description = "Run all tests"

[tasks.lint]
run = "golangci-lint run ./... --new-from-rev ''"
description = "Run linter"

[tasks.fmt]
run = "go fmt ./..."
description = "Format code"

[tasks.setup]
run = """
go mod download
mise install
lefthook install
"""
description = "Setup development environment"
